export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
export const USER_POSTSCOUNT_STATE_CHANGE = 'USER_POSTSCOUNT_STATE_CHANGE'
export const USER_FOLLOWINGCOUNT_STATE_CHANGE = 'USER_FOLLOWINGCOUNT_STATE_CHANGE'
export const USER_FOLLOWERSCOUNT_STATE_CHANGE = 'USER_FOLLOWERSCOUNT_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'



